language: android
android:
  components:
    - build-tools-19.1.0
    - android-8
  licenses:
    - android-sdk-license-5be876d5

script:
  - TERM=dumb gradle build --stacktrace
  - cd sampleApp; TERM=dumb gradle build --stacktrace
